### ISSUE TITLE
how to DDOS specific ip address 

### ISSUE THREAD

**Issue by devins-07** [UBISOFT-1/AnonymousPAK-DDoS#1]
how do i DDoS a specific ip address instead of a website?

**Comment by pelaajahacks** [comment]
Stressthem.to is a good booter/ddoser

**Comment by UBISOFT-1** [comment]
@devins-07 It should only be done if you have permission, and in that case, if the website is protected by DDoS Protection you might wanna use CloudFail or some tool like that for you Pentesting Client :)

**Comment by UBISOFT-1** [comment]
@devins-07 If you want to use this tool, do this in website input. `http://your_ip` i.e. `http://192.168.1.1`
